ALTER TABLE "Trip"
ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL DEFAULT 'Untitled Trip',
ADD COLUMN IF NOT EXISTS "description" TEXT,
ADD COLUMN IF NOT EXISTS "placeInfo" JSONB,
ADD COLUMN IF NOT EXISTS "steps" JSONB,
ADD COLUMN IF NOT EXISTS "travelCars" JSONB,
ADD COLUMN IF NOT EXISTS "flightSegments" JSONB,
ADD COLUMN IF NOT EXISTS "agendaItems" JSONB,
ADD COLUMN IF NOT EXISTS "packingSections" JSONB;

UPDATE "Trip"
SET "title" = "destination"
WHERE "title" = 'Untitled Trip';
